### ISSUE TITLE
feat: expose getter/setters for GAMESCOPECTRL_BASELAYER_APPID

### ISSUE THREAD

**Issue by R1kaB3rN** [ShadowBlip/gamescope-dbus#8]
[umu-launcher](https://github.com/Open-Wine-Components/umu-launcher) uses [python-xlib](https://github.com/python-xlib/python-xlib) to access window values set by gamescope, and to monitor for state changes on the root window whenever the `GAMESCOPECTRL_BASELAYER_APPID` property changes. `gamescope-dbus` doesn't seem to provide methods to retrieve or set a value for `GAMESCOPECTRL_BASELAYER_APPID`, and I want to know if a pull request would be OK to allow access to this property.

**Comment by pastaq** [comment]
Sure, sounds useful
